wind_oa/dashboard/urls.py
from django.urls import path, include
from .views import mainView, downloadView, readingView

app_name = 'dashboard'

urlpatterns = [path('', mainView, name='home'),
               path('download', downloadView, name='dbconnect'),
               path('readings', readingView, name='readings'), ]

wind_oa/wind_oa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dashboard.urls", namespace='dashboard')),
]

wind_oa/dashboard/models.py
from django.db import models


class Customer(models.Model):

    customer_name = models.CharField(max_length=50)

    def __str__(self):
        return self.customer_name


# model for Edc mapping
class EDCModel(models.Model):

    code = models.CharField(max_length=3)
    place = models.CharField(max_length=25)

    def __str__(self):

        return self.code


# Model for customer mapping

class ServiceGroup(models.Model):

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    serviceNumber = models.CharField(max_length=12, unique=True)
    edc = models.ForeignKey(EDCModel, on_delete=models.CASCADE)

    def __str__(self):

        return self.serviceNumber


class Readings(models.Model):

    consumerID = models.CharField(max_length=12)
    statementMonth = models.CharField(max_length=2, blank=True)
    statementYear = models.CharField(max_length=4, blank=True)
    impUnitsC1 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    impUnitsC2 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    impUnitsC3 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    impUnitsC4 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    impUnitsC5 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    expUnitsC1 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    expUnitsC2 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    expUnitsC3 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    expUnitsC4 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    expUnitsC5 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    netUnitsC1 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    netUnitsC2 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    netUnitsC3 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    netUnitsC4 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    netUnitsC5 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    bankingC1 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    bankingC2 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    bankingC3 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    bankingC4 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    bankingC5 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    chargesC002 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    chargesC003 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    chargesC004 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    chargesC005 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    chargesC006 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    chargesC007 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    chargesC001 = models.DecimalField(max_digits=12, decimal_places=2, blank=True)

    def __str__(self):

        return self.consumerID + '_' + self.statementMonth + self.statementYear

wind_oa/dashboard/views.py
from django.shortcuts import render
from .api import main
from django.http import HttpResponse
from .models import ServiceGroup, Readings
from django.db import IntegrityError

# Create your views here.


def mainView(request):

    return render(request, 'dashboard/index.html')


def downloadView(request):

    month = request.GET.get('month')
    year = request.GET.get('year')
    consumer = request.GET.get('customer')
    consumerList = []

    consumer_query = ServiceGroup.objects.filter(customer__customer_name=consumer)
    print(consumer_query)
    for consumer in consumer_query:
        consumerList.append({'EDC': consumer.edc.code, 'id': consumer.serviceNumber})

    data = main(month, year, consumerList)

    try:
        for i in data:
            print(len(i))
            cursor = Readings.objects.create(consumerID=i[0], statementMonth=i[1], statementYear=i[2], impUnitsC1=i[3], impUnitsC2=i[4], impUnitsC3=i[5], impUnitsC4=i[6], impUnitsC5=i[7], expUnitsC1=i[8], expUnitsC2=i[9], expUnitsC3=i[10], expUnitsC4=i[11], expUnitsC5=i[12], netUnitsC1=i[13], netUnitsC2=i[14], netUnitsC3=i[15], netUnitsC4=i[16], netUnitsC5=i[17], bankingC1=i[18], bankingC2=i[19], bankingC3=i[20], bankingC4=i[21], bankingC5=i[22], chargesC002=i[23], chargesC003=i[24], chargesC004=i[25], chargesC005=i[26], chargesC006=i[27], chargesC007=i[28], chargesC001=i[29])
            cursor.save()

    except:
        pass

    return HttpResponse('success')


def readingView(request):

    month = request.POST.get('month')
    year = request.POST.get('year')
    customer = request.POST.get('customer')

    reading = Readings.objects.filter(statementMonth=month)
    timeperiod = {'month': month, 'year': year}
    return render(request, 'dashboard/readings.html', {'readings': reading, 'time': timeperiod})

wind_oa/templates/dashboard/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" media="screen,projection" />
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>

<body>
    <!-- nav bar fixed -->
    <nav>
        <div class="nav-wrapper indigo">
            <a href="#!" class="brand-logo">Web Application AMR</a>
            <ul class="right hide-on-med-and-down">
                <li><a class="waves-effect waves-light btn orange text-clack" href="#">Sign-out</a></li>
            </ul>
        </div>
    </nav>
    <!-- main section -->
    <div class="row">

        <div class="col s12 m2 l2 " style="padding: 0px">
            <div class="col l12" style="padding-top: 100px;">
                <a href="{% url 'dashboard:home' %}" class="waves-effect waves-light  indigo darken-1 btn" style="width:100%">Dashboard</a>
            </div>
            <div class="col l12" style="padding-top: 10px;">
                <a class="waves-effect waves-light  indigo darken-1 btn" style="width:100%">Allotment</a>
            </div>
            <div class="col l12" style="padding-top: 10px;">
                <a class="waves-effect waves-light  indigo darken-1 btn" style="width:100%">Settings</a>
            </div>
        </div>



        <div class="col s12 m10 l10">
            {% block main %}
            <!-- Teal page content  -->
            <div class="container" style="display: flex; justify-content: flex-end; margin-top: 15px">
                <a class="waves-effect waves-light btn modal-trigger" href="#modal1">ConnectDB</a>
                <!-- Modal Structure -->
                <div id="modal1" class="modal" style="height:500px">
                    <div class="modal-content">
                        <h5 class="center-align">Download Current Month data</h5>
                        <div class="col s12 m6 l12">
                            <div class="input-field col s12">
                                <select id ="customer">
                                    <option  value=""selected>select Customer</option>
                                    <option value="Nupower">Nupower</option>
                                    <option value="Echanda">Echanda</option>
                                </select>
                                <label>Customer</label>
                            </div>
                        </div>
                        <div class="col s12 m6 l6">
                            <div class="input-field col s12">
                                <select id="month">
                                    <option value="" disabled selected>select Month</option>
                                    <option value="01">January</option>
                                    <option value="02">Febuary</option>
                                    <option value="03">March</option>
                                    <option value="04">April</option>
                                    <option value="05">May</option>
                                    <option value="06">June</option>
                                    <option value="07">July</option>
                                    <option value="08">August</option>
                                    <option value="09" disabled>September</option>
                                    <option value="10" disabled>October</option>
                                    <option value="11" disabled>November</option>
                                    <option value="12" disabled>December</option>
                                </select>
                                <label>Month</label>
                            </div>
                        </div>
                        <div class="col s12 m6 l6">
                            <div class="input-field col s12">
                                <select id="year">
                                    <option  value=""selected>select year</option>
                                    <option value="2019">2019</option>
                                </select>
                                <label>year</label>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <a class="modal-close waves-effect waves-green btn-flat" id="btn-dbc">Download</a>
                    </div>
                </div>
            </div>
            <div class="card  indigo lighten-5" style="margin-left: 75px;margin-top: 100px; width: 80%">
                <div class="row">





                <form method="POST" action="{% url 'dashboard:readings' %}" id ='myform'>
                    {% csrf_token %}
                        <div class="col s12 m6 l12">
                            <div class="input-field col s12">
                                <select id='d-customer'>
                                    <option value="" disabled selected>select Customer</option>
                                    <option value="2019">Nupower</option>
                                    <option value="2019">Echanda</option>
                                </select>
                                <label>Customer</label>
                            </div>

                            <input type="hidden"  name="customer", value="" id='d-cus'>

                        </div>
                        <div class="col s12 m6 l6">
                            <div class="input-field col s12">
                                <select id ='d-month'>
                                    <option value="" disabled selected>select Month</option>
                                    <option value="01">January</option>
                                    <option value="02">Febuary</option>
                                    <option value="03">March</option>
                                    <option value="04">April</option>
                                    <option value="05">May</option>
                                    <option value="06">June</option>
                                    <option value="07">July</option>
                                    <option value="08">August</option>
                                    <option value="09" disabled>September</option>
                                    <option value="10" disabled>October</option>
                                    <option value="11" disabled>November</option>
                                    <option value="12" disabled>December</option>
                                </select>
                                <label>Month</label>
                            </div>
                            <input type="hidden" name="month", value="" id='d-mon'>
                        </div>

                        <div class="col s12 m6 l6">
                            <div class="input-field col s12">
                                <select id ='d-year'>
                                    <option value="" disabled selected>select year</option>
                                    <option value="2019">2019</option>
                                </select>
                                <label>year</label>
                            </div>
                            <input type="hidden" name="year", value="" id='d-yr'>
                        </div>

                        <div class="col s12 m6 l12">
                            <div class="input-field col s12" style="display: flex; justify-content: center;">
                                <input type="submit" name="submit" id="sub-btn">
                            </div>
                        </div>

                </form>

                </div>

            </div>
            {% endblock %}
        </div>


        <!--JavaScript at end of body for optimized loading-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

        <script type="text/javascript">
        $(document).ready(function() {

            $('select').formSelect();
            $('.fixed-action-btn').floatingActionButton();
            $('.modal').modal();

            $("#btn-dbc").click(function(){


                var month = $("#month").val()
                var year = $("#year").val()
                var customer = $("#customer").val()

                console.log(month, year, customer)

                $.ajax({

                    type:'get',
                    url :"{% url 'dashboard:dbconnect' %}",
                    data: {'month':month, 'year':year, 'customer':customer},
                    success: function(data){

                        console.log(data)
                    }

                })


            });

            $("#sub-btn").click(function(){

                    var customer = $('#d-customer').val()
                    var month = $('#d-month').val()
                    var year = $("#d-year").val()

                    console.log(customer, month, year)

                    $('#d-cus').val(customer)
                    $('#d-mon').val(month)
                    $("#d-yr").val(year)

                    $("#myform").submit()

            });





        });
        </script>
</body>

</html>

<!--
             <div class="fixed-action-btn">
                <a class="btn-floating btn-large red">
                    <i class="large material-icons">menu</i>
                </a>
                <ul>
                    <li><a class="btn-floating red"><i class="material-icons">local_printshop</i></a></li>
                    <li><a class="btn-floating green"><i class="material-icons">file_download</i></a></li>

                </ul>
            </div>
        </div> -->

wind_oa/templates/dashboard/readings.html
{% extends 'dashboard/index.html' %}
{% load static %}

{% block main %}

<h4 class="center-text">Readings table {{ time.month }} / {{ time.year }}</h4>

<div class="card  green accent-1 lighten-3" style="margin-top: 30px">
                <table class="highlight">
                    <thead>
                        <tr>
                            <th>consumer ID</th>
                            <th>Imp-C1</th>
                            <th>Imp-C2</th>
                            <th>Imp-C3</th>
                            <th>Imp-C4</th>
                            <th>Imp-C5</th>
                            <th>Exp-C1</th>
                            <th>Exp-C2</th>
                            <th>Exp-C3</th>
                            <th>Exp-C4</th>
                            <th>Exp-C5</th>
                            <th>Net-C1</th>
                            <th>Net-C2</th>
                            <th>Net-C3</th>
                            <th>Net-C4</th>
                            <th>Net-C5</th>
                        </tr>
                    </thead>
                    <tr>
                    </tr>
                    <tbody>
                        {% for reading in readings %}
                            <tr>
                            <td>{{ reading.consumerID}}</td>
                            <td>{{ reading.impUnitsC1}}</td>
                            <td>{{ reading.impUnitsC2}}</td>
                            <td>{{ reading.impUnitsC3}}</td>
                            <td>{{ reading.impUnitsC4}}</td>
                            <td>{{ reading.impUnitsC5}}</td>
                            <td>{{ reading.expUnitsC1}}</td>
                            <td>{{ reading.expUnitsC2}}</td>
                            <td>{{ reading.expUnitsC3}}</td>
                            <td>{{ reading.expUnitsC4}}</td>
                            <td>{{ reading.expUnitsC5}}</td>
                            <td>{{ reading.netUnitsC1}}</td>
                            <td>{{ reading.netUnitsC2}}</td>
                            <td>{{ reading.netUnitsC3}}</td>
                            <td>{{ reading.netUnitsC4}}</td>
                            <td>{{ reading.netUnitsC5}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>


{% endblock %}